language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t kiranvits/simple-web-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true kiranvits/simple-web-docker npm run test  

# enable the below code for aws deployment
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "docker"
#   env: "docker-env"
#   bucket_name: "elasticbeanstalk-us-east-2-923445559289"
#   bucket_path: "docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY