language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t kiranvits/simple-web-docker .

script:
  - docker run -e CI=true kiranvits/simple-web-docker npm run test
